# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qiS7AYApGbAF9RcU_FwYL37k1CRkjYQT
"""

dados_funcionario = {'nomes':'joão','idade':32,'altura':1.65, 'ativo':True,'dependentes':{'filhos':10,'conjugue':True}}
dados_funcionario['salario']=1500
dados_funcionario['dependentes']['filhos']*100+ dados_funcionario['dependentes']['conjugue']*100+dados_funcionario['salario']
dados_salvo = dados_funcionario.copy()
dados_funcionario.get('nome')

c = ['nome','idade','endereco']
v = ['bruna','28','rua das rosas'] 
dicionario = dict(zip(c,v)) 
print(dicionario)