# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ITyKQ-76prpv1jQAVGIg4uaKLgXn3rxW
"""

x=set()
y=set()
while True:
    a=set(input('Insira um dado aqui: '))
    b=set(input('Insira um dado aqui: '))
    c=str(input('Para sair digite SAIR! ')).upper()
    if c != 'SAIR':
        x=a.union(a)
        y=b.union(b)
    else:
        x=a.union(a)
        y=b.union(b)
        break
print(x,y)
while True:
      res=int(input('''Digite 1 para fazer interseção
      Para fazer o descard de um valor digite 2
      Digite 3 para saber se ele tem algo em comum
      Digite 4 para saber se um conjunto é super ou sub de outro
      '''))
      if res == 1:
         z=x.interservtion
         print(f'A inerseção dos dois é {z} ')
      elif res == 2:
          esc=input('escolha o conjuto')
          if esc == x:
            esc = x
          else:
            esc = y
          disc = input('Digite o que pricisa descartar do conjunto')
          z.discard(esc)
          print(esc)
      elif res == 3:
          iSdis =  y.isdisjoint(x)
      if iSdis == True:
          print(f'Não tem nada em comun entre os conjuntos x:{x} e y {y}')    
      elif res == 4:
        esc = x.issubset(y) 
        esc = y.issubset(x)  
      print(esc)

nome = {'banana','maçã','uva'}
a=['banana']
a

dados_funcionario = {'nomes':'joão','idade':32,'altura':1.65,'ativo':True'dependentes'{'filhos':0,'conjuge':false}}
nome