# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1buPaapz1WYQHk9nLrXpNAIc9dmNE1cmx
"""

letras = {'a','b','c','a','d','c','a','f','g'} 
print(letras)

frutas = {'uva', 'maçã', 'tangerina', 'uva',}
frutas.clear()
print(f'Aqui estão em uma lista: {frutas}')
frutas.clear()
frutas = set(frutas)
print(f'Agora estão em uma lista: {frutas}')

frutas = {'uva', 'maçã', 'tangerina', 'uva',}
verduras = {'cebola','pimentão'}
vegetais = frutas | verduras
print(vegetais)

frutas = {'uva', 'maçã', 'tangerina', 'uva',}

diferenca = mobile.difference(web)
print(diferenca)

web = {'html','kavascript','python','css'}
mobile = {'fluter','python','kotlin','javascript'}
diferenca1 = web - mobile
diferenca2 = mobile - web
print(diferenca1, '-' , diferenca2)

web = {'html','python','da','ka'}
mobile = {'fluter','python','kotlin','javascript'}
x = web.issubset(mobile)        
print(x)

web = {'html','kavascript','python','css'}
mobile = {'python','javascript'}
x =
print(x)

#união
a=set(input('Insira um dado aqui: '))
b=set(input('Insira um dado aqui: '))
print(a,b)

while True:
    a=set(input('Insira um dado aqui: '))
    b=set(input('Insira um dado aqui: '))
    c=str(input(Para sair digite SAIR!))
    if c != 'SAIR':
        a.Union(a)
        b.union(b)
    else:
        a.Union(a)
        b.union(b)
        break
print(a,b)

x=set()
y=set()
while True:
    a=set(input('Insira um dado aqui: '))
    b=set(input('Insira um dado aqui: '))
    c=str(input('Para sair digite SAIR! ')).upper()
    if c != 'SAIR':
        x.Union(a)
        y.union(b)
    else:
        x.Union(a)
        y.union(b)
        break
print(a,b)

dados_funcionario = {'nomes':'joão','idade':32,'altura':1.65,'ativo':True'dependentes'{'filhos':0,'conjuge':false}}

