# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1shvQMqOCTUHTjmI5jEh3XYthgGyOxF0Y
"""

a={1,2,3,4}
b={1,4,5,6}
c=a.union(b)
c

dados_funcionario = {'nomes:'joão','idade':32,'altura':1.65', 'ativo':True'dependentes'{'filhos':0,'conjuge':False}}
nome



dados_funcionario['dependentes']['filhos']*100+ dados_funcionario['dependentes']['conjugue']*100